### ISSUE TITLE
Requests for Applied Energistics 2

### ISSUE THREAD

**Issue by meitangdehulu** [ChiselsAndBits/Chisels-and-Bits-Sharing#4]
I think you look at [this](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3541) first.
I tried to get in touch with you at AE's github and your Twitter, but it didn't go well, I got this Issue.
I hope I can repost it in a Chinese BBS which is called MCBBS,to promote it to more Chinese players..
I will not use this as a profit, I will keep everything you ask, such as the author's name or other.
Can I reprint your mod to another Chinese forum?
Due to network problems,can I create a Download link of China?
Looking forward to hearing from you.

**Comment by AlgorithmX2** [comment]
I don't mind, I prefer to keep re-hosting to a minimum since there is a lot of nefarious sites out there trying to redistribute mods with ill-intent.

However these are just precautions to help keep people from getting bad copies. as was stated on the other issue, most new versions of AE2 are LGPL, and those are fine regardless, you can also re-use the content on the website, or translate it as needed. I don't really mind.

**Comment by meitangdehulu** [comment]
@AlgorithmX2 
Of course, I will do your request.

**Comment by keeptpa** [comment]
@AlgorithmX2 I came from mcmod.cn ,have the same propose,so...can i repost AE2 on mcmod.cn ?(This is a chinese modwiki.)

**Comment by AlgorithmX2** [comment]
Same applies to anyone, If possible use the existing download urls, since as stated above, I prefer to keep re-hosting to a minimum.

**Comment by keeptpa** [comment]
@AlgorithmX2 Thank you for your reply
